uploads = []
generated = []

[[outputs]]
id = "SbZiE_vnt86JOdBeZATuN"
uri = "file:///tmp/last_story.pdf"
type = "pdf"
title = "Космическое Приключение Максима (PDF)"

[[outputs]]
id = "xjAApvhnzRMMdnAcWKmfV"
uri = "file:///tmp/final_story.pdf"
type = "pdf"
title = "Космическое Приключение Максима (с новым дизайном)"

[[outputs]]
id = "nhBu84q_hkdKnqtBxKGWb"
uri = "file:///tmp/working_pdf.pdf"
type = "pdf"
title = "Космическое приключение Максима (исправленный PDF)"

[[outputs]]
id = "4hdtJ2BltGLWLBEm_s0kY"
uri = "file:///tmp/updated.pdf"
type = "pdf"
title = "Обновлённый PDF с улучшенными отступами"
